### ISSUE TITLE
[BUG] Rats mod kills the server

### ISSUE THREAD

**Issue by DeFYzz** [YahiaTGF/MC-Odyssey-2#2]
**Describe the bug**
It appears that as soon as a demon rat spawns, the server gets stuck.

**To Reproduce**
1. Play the modpack
2. As soon as a demon rat spawns, that server doesnt respond anymore

**Expected behavior**
Entity spawns and I can continue

**Screenshots**

**Information (please complete the following information):**
 - OS: Win10
 - Modpack Version 0.0.4 BETA
 - 10GB
 - Java 8

**Additional context**
There is actually no information on why this happens so I used VisualVM to find out why the server thread isnt working anymore and found this in a thread dump

My suggestion is to remove the Rats mod or disable demon rats spawns. Also when looking at the Rats mod issues, this is a long known issue. Note: This also happens in a custom created modpack

`
"Worker-Main383" #706 daemon prio=1 os_prio=-2 tid=0x000001e489967000 nid=0x3ea0 waiting on condition [0x00000065838fe000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006e453d868> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.CompletableFuture$Signaller.block(Unknown Source)
        at java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
        at java.util.concurrent.CompletableFuture.waitingGet(Unknown Source)
        at java.util.concurrent.CompletableFuture.join(Unknown Source)
        at net.minecraft.world.server.ServerChunkProvider.getChunkOffThread(ServerChunkProvider.java:1157)
        at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(ServerChunkProvider.java:1122)
        at net.minecraft.world.World.func_217353_a(MixinWorldRedstone.java:167)
        at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:814)
        at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754)
        at com.github.alexthe666.rats.server.events.CommonEvents.onEntityJoinWorld(CommonEvents.java:238)
        at net.minecraftforge.eventbus.ASMEventHandler_2529_CommonEvents_onEntityJoinWorld_SpecialSpawn.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus$$Lambda$2568/1878497144.invoke(Unknown Source)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(ForgeEventFactory.java:216)
        at net.minecraft.world.spawner.WorldEntitySpawner.handler$cap000$forbidden_arcanus_performWorldGenSpawning(WorldEntitySpawner.java:534)
        at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:368)
        at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623)
        at net.minecraft.world.chunk.ChunkStatus.func_222602_b(ChunkStatus.java:89)
        at net.minecraft.world.chunk.ChunkStatus$$Lambda$2315/254576767.doWork(Unknown Source)
        at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240)
        at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198)
        at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524)
        at net.minecraft.world.server.ChunkManager$$Lambda$59017/278689365.apply(Unknown Source)
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
        at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522)
        at net.minecraft.world.server.ChunkManager$$Lambda$59002/712949348.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
        at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
        at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$59015/769935248.run(Unknown Source)
        at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94)
        at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137)
        at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
`

**Comment by choombdev** [comment]
Thank you for the report!
Fixed in upcoming Patch.
